Fixed get ac_id
RogerYong/bit_srun pull request #3
Opened 2018-05-29 05:23 UTC by D-VR

10.0.0.55 will always return ac_id = 1,
even when in reality it's not the correct one, leading to failure to login in some instances.

10.0.0.53 always returns the correct ac_id

2018-05-29 05:42 UTC, phy25 requested changes
`10.0.0.53` only grants access to Intranet because it redirects users to www.bit.edu.cn. Just tested with Ethernet access, and it doesn't work.

2018-05-29 06:44 UTC, D-VR commented
you are right, i just checked again over Bit Mobile. seems only BIT Web will redirect in that case. I’ll do some more research 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-05-29 07:08 UTC, D-VR commented
Bit Web has different behaviour than Ethernet/Bit Mobile. Bit Web will force redirect every url to the correct ac_id, bit mobile and ethernet default to ac_id=1 and do not redirect, this makes it a bit difficult.

maybe check for redirect, and if not default to ac_id=1?

2018-05-29 07:42 UTC, phy25 commented
It's best to use 204 response to an Internet URL to check that: https://www.v2ex.com/t/189687

2018-05-29 08:11 UTC, D-VR commented
>It's best to use a 204 response to an Internet URL to check for that: https://www.v2ex.com/t/189687

@phy25

i was thinking of using a captive portal like:
captive.apple.com
or
detectportal.firefox.com
(this one seems to be blocked for some reason though)

2018-05-29 11:57 UTC, D-VR commented
This ac_id method, works on both BIT Web and BIT Mobile, i tried changing py2 using the same method, but urllib wasnt playing nice with me, and i'm not too familiar with it.
Tell me what you think.
Logic:

get http://detectportal.firefox.com/success.txt
if no response in 0.01seconds
set ac_id = 1 
#detection if on BIT mobile or Ethernet

else if response (redirect)
set ac_id = according to redirect

#detection for BIT Web
else if response (success)
ac_id = 1 
#incase if already logged in AND site loads (which it doesnt most of the time) so script doesnt break

2018-05-30 07:45 UTC, phy25 commented
In my opinion use an address in China mainland is much better (see the v2ex link attached before). And I don't think the request to detectportal.firefox.com (Akamai CDN Japan) would finish in 10ms, maybe 1000ms is better?

2018-05-30 08:53 UTC, D-VR commented
>In my opinion use an address in China mainland is much better (see the v2ex link attached before). And I don't think the request to detectportal.firefox.com (Akamai CDN Japan) would finish in 10ms, maybe 1000ms is better?

we don’t want to get an answer to the request though. since if it connects, that means we are already online, and we don’t have to login in the first place. 

what we want is the redirect, which happens on the internal network so response time should be less than 10 ms (might increase it, depending on texting, but was sufficient in my original run)

(note, the timeout is not for a finished response, but for first received packet from server)

2018-05-30 09:30 UTC, phy25 commented
Makes sense, but I still stand for 0.05s 🙂, because some WiFi may be slower.

2018-05-30 10:06 UTC, D-VR commented
>Makes sense, but I still stand for 0.05s 🙂, because some WiFi may be slower.

@phy25

sounds good, also any idea how to implement this in urllib?

2018-05-30 11:13 UTC, RogerYong commented
How about [http://10.0.0.55/index_8.html](http://10.0.0.55/index_8.html)?

2018-05-30 11:15 UTC, D-VR commented
does 8 work for BIT mobile and ethernet?

2018-05-30 11:37 UTC, merged

2018-05-30 11:48 UTC, D-VR commented
one more thing, increasing timeout like @phy25 recommended might be a good idea, not sure how stable wifi authentication is

2018-05-31 15:07 UTC, D-VR commented
@RogerYong 50ms is advised, just had the problem where wifi was too slow resulting in wrong login using ac_id=1

btw, using the wrong ac_id, will result in you logging in, but without being able to access the internet, in addition, if you go to the correct ac_id and login (while still being logged in as the wrong ac_id) you will not be able to login, until you log off the first ac_id...

another piece of interesting behaviour:
you can log out with out supplying an ac_id (and i think with out access token)